#if !canImport(ObjectiveC)
import XCTest

extension CombineLatestCollectionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CombineLatestCollectionTests = [
        ("testBasic", testBasic),
        ("testFailure", testFailure),
        ("testFinished", testFinished),
        ("testReceiveCancel", testReceiveCancel),
        ("testReceiveSubscription", testReceiveSubscription),
        ("testValue", testValue),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CombineLatestCollectionTests.__allTests__CombineLatestCollectionTests),
    ]
}
#endif
